### ISSUE TITLE
Chest

### ISSUE THREAD

**Issue by DragonTamr34** [danikk14g/Craftologia#2]
Why does the chest recipe that uses logs create all chest types but actually does not craft anything? Are you only suppose to use the one with the lock?

**Comment by dancc7t** [comment]
Hi, sorry for the late response.
Well i noticed this a while ago, i tried different ways to keep only one recipe (the one with the lock) visible for the vanilla chest, still it shows the other (same thing happens with wooden gears), probably because several mods are trying to add their own recipes for it. 
Since only the chest and wooden gear show this problem, i am simply waiting to see if a mod update fixes it I think this is also referenced in the Guidebook.

**Comment by DragonTamr34** [comment]
Alright, thanks for the help. I was just a little confused about the recipes. I used the recipe requiring the lock and did not notice the gear needed rubber till after crafting one.

**Comment by DragonTamr34** [comment]
One more thing, do you have any tips on mining/finding ores? I have had some trouble finding iron via branch mining and only got lucky by finding some in a ravine. I am still a bit confused about the oregen in the pack.

**Comment by dancc7t** [comment]
Yes, ores generate in larger chunks but with less frenquency, so branch mining is not the most efficient way to localize/prospect ores, it takes much more time than simply exploring through caves and ravines.

Ores generate only in some biomes (iron generates in 33 different biomes), but once you know the biome you can go, in some cases, with branch mining, i say "in some cases" because there are several types of generators, so a fractal with high density along the y-axis would be more difficult to find which branch mining, which mainly scans along the x-axis.

I have to say i am still not done with the oregen. i have not finished some dimensions and i would like to improve it with more different generators and also surface "hints" that can tell you what kind of ore is underground, mainly with GTCE gravel versions of ores on the surface.

**Comment by DragonTamr34** [comment]
Ok, I am trying a new mining technique right now. It takes a while because I dig a 2x2 staircase at the chunk center and then go back and branch out at four block increments on the y-axis. I did notice a lack of seeds from grass however. Is the chance just low or disable because I am trying to get hemp seeds(both mods that add it).

**Comment by dancc7t** [comment]
I have to say column-shaped generations are one of the least common, most common one is large solid  chunk.
yes, some ppl complained about hemp seeds on discord, i myself needed more time than expected to get the bwm one, but once you have one you dont need to find anymore. i did not find what mod might be causing this but ill check again.

**Comment by DragonTamr34** [comment]
Thanks for answering my questions and helping me. I am looking forward to more updates and hope you continue to enjoy making this great modpack. Cheers!
