### ISSUE TITLE
How to access quest book?

### ISSUE THREAD

**Issue by corgiblu** [danikk14g/Craftologia#6]
You mentioned a WIP quest book and I can't seem to figure out how to get at it, or even what mod it is. Also any discord link I found is expired.

**Comment by dancc7t** [comment]
Yes, you are right, i am sorry i did not found out ftbquests was not shipped with the latest version of the pack, previous version does include it, but i recommend you to wait a couple of days until i release a new version of the pack instead of playing an old version of the pack. 
Discord link is still open (it never expires), this is the link: https://discord.gg/7Tgy2NB
