### ISSUE TITLE
Can't download modpack with Twitch

### ISSUE THREAD

**Issue by slava110** [danikk14g/Craftologia#9]
![изображение](https://user-images.githubusercontent.com/26705162/89898260-1090a800-dbe9-11ea-8353-3ddc736c0630.png)

**Comment by dancc7t** [comment]
Hello, sorry for the late reply, pack went under a big hiatus due to irl issues and i didnt read this until today. Now i am working actively again on the pack so i guess better late than never.

About your issue, i guess Modern Lights mod caused the issue because last week when i tried to add it to the pack files it warned me about it in particular, the mod itself is no longer present in the CurseForge site, so that probably caused the issue. Now the full list of mods has been reviewed and updated where applicable as of version 2.0.0 where no missing mods are present. I personally tested it last weekend and it can be downloaded without any problems.
